### ISSUE TITLE
TypeError: contactGateway is not a function

### ISSUE THREAD

**Issue by jprichter** [Sundog-Interactive/DF14-Visualforce-AngularJS-RemoteObjects#2]
First off, your talk and this code are both extremely helpful. 

I zipped it up and have it running in a development org to get a feel for it. Everything seemed to be working except for saving an edit where I get error mentioned in the title. Seems to be pointing to [this line](https://github.com/Sundog-Interactive/DF14-Visualforce-AngularJS-RemoteObjects/blob/master/src/app/contact/contact-edit-controller.js#L7).

**Comment by kulishch** [comment]
Nice catch! 

It looks like I'm using the [injected Remote Object](https://github.com/Sundog-Interactive/DF14-Visualforce-AngularJS-RemoteObjects/blob/master/src/app/app.js#L36) incorrectly throughout the code. I'm calling the CRUD methods directly off of the object returned from the service and I should be using that object to instantiate a new object (with or without details) and calling the CRUD methods that way. 

It also looks like I need to write a factory function the returns the Remote Object and not just pass it in directly.

So [this](https://github.com/Sundog-Interactive/DF14-Visualforce-AngularJS-RemoteObjects/blob/master/src/app/app.js#L36) should look something like this:

```
.service('contactGateway', function() {
return SObjectModel.ContactGateway
});
```

and [this](https://github.com/Sundog-Interactive/DF14-Visualforce-AngularJS-RemoteObjects/blob/master/src/app/contact/contact-edit-controller.js#L26) should look something like this:

```
var cg = new contactGateway();
cg.retrieve(criteria, ...)
```

All instances where `contactGateway` is calling a CRUD method other than `update` will have to be updated. I'll try and get the repo updated by the end of the week. Thanks again for catching that.

**Comment by kulishch** [comment]
@jprichter I updated the repo with a fix.

I think the `contactGateway` service should be built out a little differently than it is. It should encapsulate the Remote Objects proxy object entirely so the rest of your app doesn't even realize it's leveraging Visualforce Remote Objects. I think adding methods that map to the CRUD ones on the proxy object that take a `data` argument and a `callback` argument would be better.
