### ISSUE TITLE
Salesforce UI header is messed up when load VF page when showheader=true

### ISSUE THREAD

**Issue by contactvm** [Sundog-Interactive/DF14-Visualforce-AngularJS-RemoteObjects#4]
using bootstrap, my salesforce header and salesforce sidebar fonts are messed up when i load my VF page. So I have to the disabled header. I checked the forum, it is mentioned add your bootstrap class in your body tag, but it doesn't work. If you have tried before then can you please let me know the solution
Can anyone please help me on this
![image](https://cloud.githubusercontent.com/assets/28222701/25564733/8b5717a4-2d87-11e7-9d80-93e2cec34b61.png)

**Comment by tickylum** [comment]
Hey @contactvm, did you find a solution for this please?

**Comment by contactvm** [comment]
Yes my friend, are you facing the same issue?

Done by giving namespace to bootstrap.
for your reference

https://formden.com/blog/isolate-bootstrap

**Comment by tickylum** [comment]
Yes! Can you please tell me what was the solution? How can the include of the bootstrap affect ONLY inside the VF page and not the surrounding controls?

**Comment by contactvm** [comment]
I frwd u the link
If any doubt then call me on Skype

**Comment by tickylum** [comment]
Thanks contactvm, will review it and get back to you if I had more questions.

**Comment by contactvm** [comment]
ok sure, I hope your issue is resolved.

**Comment by kulishch** [comment]
We've used the namespace technique in the past and it works well. We have experienced issues with fonts and the grid not behaving correctly after applying the namespace to the LESS/SASS code. You have to tweak the lines that reference the <body> tag and the grid classes so that the selectors work correctly.

**Comment by contactvm** [comment]
Resolved using custom namespace for bootstrap
https://formden.com/blog/isolate-bootstrap
